-- EJERCICIO 1 --

UPDATE CENTROS
SET NUM_PLAZAS=ROUND(NUM_PLAZAS/2)
WHERE COD_CENTRO IN (SELECT COD_CENTRO FROM PROFESORES 
                    GROUP BY COD_CENTRO
                    HAVING COUNT(*)<2);

-- EJERCICIO 2 --

DELETE CENTROS
WHERE COD_CENTRO NOT IN (SELECT COD_CENTRO FROM PERSONAL)

-- EJERCICIO 3 -- 

INSERT INTO PROFESORES
SELECT COD_CENTRO, 8790055, 'Salas, Clara', 'IDIOMA' FROM PERSONAL
WHERE FUNCION='ADMINISTRATIVO'
GROUP BY COD_CENTRO HAVING COUNT(FUNCION)=1;

-- EJERCICIO 4 --

DELETE PERSONAL
WHERE COD_CENTRO IN (SELECT C.COD_CENTRO
					 FROM CENTROS C, PROFESORES P
					 WHERE NUM_PLAZAS<300 AND C.COD_CENTRO=P.COD_CENTRO
					 GROUP BY C.COD_CENTRO
					 HAVING COUNT(*)<2)

-- EJERCICIO 5 --

DELETE PROFESORES
WHERE DNI NOT IN (SELECT DNI FROM PERSONAL)

-- EJERCICIO 6 --

INSERT INTO ARTICULOS
SELECT ARTICULO, COD_FABRICANTE, PESO, 'PRIMERA', PRECIO_VENTA, PRECIO_COSTO, EXISTENCIAS
FROM ARTICULOS
WHERE COD_FABRICANTE=(SELECT COD_FABRICANTE FROM FABRICANTES WHERE PAIS='FRANCIA')

-- EJERCICIO 8 --

INSERT INTO TIENDAS
VALUES ('5555-C', 'Merkadona', 'C/Ortega y Gasset, 44', 'Madrid', 'MADRID', '28080');

INSERT INTO PEDIDOS
SELECT '5555-C', ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, SYSDATE, 20
FROM ARTICULOS

-- EJERCICIO 9 --

INSERT INTO TIENDAS
VALUES ('5555-C', 'Merkadona', 'C/Manzano, 4', 'Sevilla', 'SEVILLA', '41004');

INSERT INTO TIENDAS
VALUES ('5556-C', 'Ahorra menos', 'C/Abedul, 3', 'Sevilla', 'SEVILLA', '41003');

INSERT INTO PEDIDOS
SELECT '5555-C', ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, SYSDATE, 30
FROM ARTICULOS
WHERE COD_FABRICANTE=(SELECT COD_FABRICANTE FROM FABRICANTES WHERE NOMBRE='GALLO')

INSERT INTO PEDIDOS
SELECT '5556-C', ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, SYSDATE, 30
FROM ARTICULOS
WHERE COD_FABRICANTE=(SELECT COD_FABRICANTE FROM FABRICANTES WHERE NOMBRE='GALLO')

-- EJERCICIO 10 --

INSERT INTO VENTAS

SELECT NIF, ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, SYSDATE, 10
FROM TIENDAS, ARTICULOS
WHERE PROVINCIA = 'TOLEDO' AND CATEGORIA = 'Primera';

-- EJERCICIO 11 --

INSERT INTO PEDIDOS

SELECT DISTINCT '5555-B', ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, SYSDATE, 10
FROM VENTAS GROUP BY ARTICULO, COD_FABRICANTE, PESO, CATEGORIA
HAVING SUM(UNIDADES_VENDIDAS)>30;

-- EJERCICIO 12 --

UPDATE TIENDAS
SET (NIF, NOMBRE, DIRECCION, POBLACION, PROVINCIA, CODPOSTAL) 
= (SELECT * FROM TIENDAS WHERE NIF = '2222-A')
WHERE NIF = '1111-A'

-- EJERCICIO 13 --

UPDATE ARTICULOS
SET CATEGORIA='Segunda'
WHERE CATEGORIA='Primera' 
AND COD_FABRICANTE=(SELECT COD_FABRICANTE FROM FABRICANTES WHERE PAIS='ITALIA') 

-- EJERCICIO 15 --

DELETE TIENDAS
WHERE NIF NOT IN (SELECT DISTINCT NIF FROM VENTAS)

SELECT * FROM VENTAS


-- EJERCICIO 16 --

DELETE ARTICULOS
WHERE ARTICULO NOT IN (SELECT ARTICULO FROM VENTAS UNION SELECT ARTICULO FROM PEDIDOS)
AND PESO NOT IN (SELECT PESO FROM VENTAS UNION SELECT PESO FROM PEDIDOS)

