-- EJERCICIO 3 -- 
INSERT INTO PROFESORES
SELECT COD_CENTRO, 8790055, 'Salas, Clara', 'IDIOMA' FROM PERSONAL
WHERE FUNCION='ADMINISTRATIVO'
GROUP BY COD_CENTRO HAVING COUNT(FUNCION)=1;

-- EJERCICIO 
INSERT INTO ARTICULOS
SELECT ARTICULO, COD_FABRICANTE, PESO, 'PRIMERA', PRECIO_VENTA, PRECIO_COSTO, EXISTENCIAS
FROM ARTICULOS
WHERE COD_FRABRICANTE=(SELECT COD_FABRICANTE FROM FABRICANTES WHERE PAIS='FRANCIA')

DESC FABRICANTES