-- EJERCICIO 1
SELECT APELLIDO||' ES '||OFICIO "PUESTO DE TRABAJO" FROM EMPLE

-- EJERCICIO 2
SELECT RPAD ('X', 5, '*.') "Der", LPAD ('X', 5, '*.') "Izq" FROM DUAL;
-- 

-- EJERCICIO 3
SELECT REPLACE(REPLACE(TITULO,'.',''),'"','') FROM MISTEXTOS
SELECT LTRIM(RTRIM(TITULO,'".'),'"') FROM MISTEXTOS

-- EJERCICIO 4
SELECT LOWER(SUBSTR(APELLIDO,1,1))||SUBSTR(APELLIDO,2) FROM EMPLE

-- EJERCICIO 5
SELECT REPLACE(TITULO,'."') FROM MISTEXTOS

-- EJERCICIO 6
SELECT LENGTH(TEMA) FROM LIBRERIA

-- EJERCICIO 7
SELECT FECHA_ALT, FECHA_ALT-yy3 FROM EMPLE
