-- EJERCICIO 1
SELECT TRUNC(AVG(SALARIO),2)"MEDIA SUELDO", COUNT(COMISION) "COMISIONES", MAX(SALARIO) "SALARIO MAXIMO", MIN(SALARIO)"SALARIO MINIMO" 
FROM EMPLE WHERE DEPT_NO='30'

-- EJERCICIO 2
SELECT TEMA FROM LIBRERIA WHERE TEMA LIKE '%E%' AND EJEMPLARES=(SELECT MAX(EJEMPLARES) FROM LIBRERIA WHERE TEMA LIKE '%E%')

-- EJERCICIO 3
SELECT RPAD(REPLACE(REPLACE(TITULO,'.',''),'"',''),40,'-^')"RESULTADO" FROM MISTEXTOS

-- EJERCICIO 4
SELECT LOWER((REPLACE(REPLACE(TITULO,'.',''),'"',''))) FROM MISTEXTOS
SELECT LOWER(LTRIM(RTRIM(RTRIM(TITULO,'"'),'.'),'"')) FROM MISTEXTOS

-- EJERCICIO 5
SELECT AUTOR, SUBSTR(AUTOR,1,INSTR(AUTOR,',')-1)"APELLIDO" FROM LIBROS

-- EJERCICIO 6
SELECT AUTOR, SUBSTR(AUTOR,INSTR(AUTOR,',')+1)"NOMBRE" FROM LIBROS

-- EJERCICIO 7
SELECT SUBSTR(AUTOR,1,INSTR(AUTOR,',')-1)"APELLIDO", SUBSTR(AUTOR,INSTR(AUTOR,',')+1)"NOMBRE" FROM LIBROS

-- EJERCICIO 8
SELECT TITULO FROM LIBROS ORDER BY LENGTH(TITULO)

-- MOSTRAR SIGLAS (APELLIDO+NOMBRE(C.C.))
SELECT CONCAT(SUBSTR(AUTOR,1,1)||'.', SUBSTR(SUBSTR(AUTOR,INSTR(AUTOR,',')+1),2,1)||'.')"INICIALES"  FROM LIBROS

-- EJERCICIO 9
SELECT NOMBRE, FECHANAC, 
TO_CHAR(FECHANAC,'"Nació el "dd" de "')||RTRIM(TO_CHAR(FECHANAC,'month'))||TO_CHAR(FECHANAC,'" de "yyyy') "FECHA FORMATEADA"
FROM NACIMIENTOS


SELECT NOMBRE, FECHANAC, REGEXP_REPLACE(TO_CHAR(FECHANAC, '"Nació el "dd" de "month" de "yyyy'),'*  *',' ') FROM NACIMIENTOS
-- EJERCICIO 10
SELECT TEMA, SUBSTR(RTRIM(TEMA),-1)"ULTIMA LETRA", LENGTH(RTRIM(TEMA))"CARACTERES TEMA" FROM LIBRERIA ORDER BY TEMA

-- EJERCICIO 11
SELECT INITCAP(RTRIM(NOMBRE))||REGEXP_REPLACE(TO_CHAR(FECHANAC, '" nació el "dd" de "month" de "yyyy"."'),'*  *',' ') FROM NACIMIENTOS

-- EJERCICIO 12
SELECT TO_CHAR(TO_DATE('010712','DDMMYY'),'MONTH')"MES MAYUS" FROM DUAL

-- EJERCICIO 13
SELECT DECODE(EJEMPLARES,7,'SEVEN',TEMA)"SEVEN" FROM LIBRERIA

-- EJERCICIO 14
SELECT APELLIDO FROM EMPLE WHERE FECHA_ALT<ADD_MONTHS(SYSDATE,-180)

SELECT APELLIDO FROM EMPLE WHERE (MONTHS_BETWEEN(SYSDATE,FECHA_ALT)/12)>15
-- EJERCICIO 15
SELECT APELLIDO FROM EMPLE 
WHERE DEPT_NO IN (SELECT DEPT_NO FROM DEPART WHERE DNOMBRE='VENTAS') AND FECHA_ALT<ADD_MONTHS(SYSDATE,-192)

-- EJERCICIO 16
SELECT APELLIDO, SALARIO, DEPT_NO FROM EMPLE E
WHERE SALARIO = (SELECT MAX(SALARIO) FROM EMPLE WHERE DEPT_NO=E.DEPT_NO);


-- EJERCICIO 17
SELECT APELLIDO SALARIO, DEPT_NO FROM EMPLE E
WHERE SALARIO > (SELECT AVG(SALARIO) FROM EMPLE WHERE DEPT_NO=E.DEPT_NO);
  

