-- EJERCICIO 1 -- 
SELECT OFICIO, SUM(SALARIO)"SUMA SALARIOS" FROM EMPLE
WHERE DEPT_NO = (SELECT DEPT_NO FROM DEPART WHERE DNOMBRE = 'VENTAS')
GROUP BY OFICIO

-- EJERCICIO 2 --
SELECT APELLIDO FROM EMPLE E WHERE SALARIO = (SELECT AVG(SALARIO) FROM EMPLE WHERE E.DEPT_NO=DEPT_NO)

-- EJERCICIO 3 --
SELECT DEPT_NO, COUNT(*)"Nº EMPLEADOS" FROM EMPLE WHERE OFICIO='EMPLEADO' GROUP BY DEPT_NO

-- EJERCICIO 4 --
SELECT DEPT_NO FROM EMPLE WHERE OFICIO='EMPLEADO' 
GROUP BY DEPT_NO HAVING COUNT(*)=(SELECT MAX(COUNT(*)) FROM EMPLE WHERE OFICIO='EMPLEADO' GROUP BY DEPT_NO)

-- EJERCICIO 5 --
SELECT E.DEPT_NO, DNOMBRE, COUNT(*)"Nº EMPLEADOS" FROM EMPLE E, DEPART D 
WHERE OFICIO='EMPLEADO' AND E.DEPT_NO=D.DEPT_NO GROUP BY E.DEPT_NO, DNOMBRE
HAVING COUNT(*)=(SELECT MAX(COUNT(*)) FROM EMPLE WHERE OFICIO='EMPLEADO' GROUP BY DEPT_NO)

-- EJERCICIO 6 --
SELECT DEPT_NO FROM EMPLE E GROUP BY DEPT_NO, OFICIO HAVING COUNT(DEPT_NO)>2

-- EJERCICIO 10 --
SELECT C.NOMBRE, P.ESPECIALIDAD, COUNT(P.DNI) FROM CENTROS C, PROFESORES P
WHERE C.COD_CENTRO = P.COD_CENTRO (+)
GROUP BY C.NOMBRE, P.ESPECIALIDAD

-- EJERCICIO 11 --
SELECT C.NOMBRE, COUNT (P.DNI)
FROM CENTROS C, PERSONAL P
WHERE C.COD_CENTRO = P.COD_CENTRO (+)
GROUP BY C.NOMBRE

-- EJERCICIO 12 --
SELECT ESPECIALIDAD, COUNT(DNI) FROM PROFESORES GROUP BY ESPECIALIDAD 
HAVING COUNT(DNI)= (SELECT MIN(COUNT(*)) FROM PROFESORES GROUP BY DNI)

-- EJERCICIO 13 --
SELECT B.NOMBRE_BANC, COUNT(S.COD_SUCUR) 
FROM BANCOS B, SUCURSALES S
WHERE B.COD_BANCO = S.COD_BANCO
GROUP BY B.NOMBRE_BANC 
HAVING COUNT(S.COD_SUCUR) = (SELECT MAX(COUNT(COD_SUCUR)) FROM SUCURSALES GROUP BY COD_BANCO)

-- EJERCICIO 14 --
SELECT B.NOMBRE_BANC, S.NOMBRE_SUCUR, SUM(C.SALDO_DEBE), SUM(C.SALDO_HABER)
FROM SUCURSALES S, CUENTAS C, BANCOS B
WHERE B.POBLACION='GUADALAJARA' AND B.COD_BANCO = S.COD_BANCO = C.COD_BANCO
GROUP BY B.NOMBRE_BANC
