-- EJERCICIO 1
SELECT TRUNC(AVG(SALARIO),2)"MEDIA SUELDO", COUNT(COMISION) "COMISIONES", MAX(SALARIO) "SALARIO MAXIMO", MIN(SALARIO)"SALARIO MINIMO" 
FROM EMPLE WHERE DEPT_NO='30'

-- EJERCICIO 2
SELECT TEMA FROM LIBRERIA WHERE TEMA LIKE '%E%' AND EJEMPLARES=(SELECT MAX(EJEMPLARES) FROM LIBRERIA WHERE TEMA LIKE '%E%')

-- EJERCICIO 3
SELECT RPAD(REPLACE(REPLACE(TITULO,'.',''),'"',''),40,'-^')"RESULTADO" FROM MISTEXTOS

-- EJERCICIO 4
SELECT LOWER((REPLACE(REPLACE(TITULO,'.',''),'"',''))) FROM MISTEXTOS
SELECT LOWER(LTRIM(RTRIM(RTRIM(TITULO,'"'),'.'),'"')) FROM MISTEXTOS

-- EJERCICIO 5
SELECT AUTOR, SUBSTR(AUTOR,1,INSTR(AUTOR,',')-1)"APELLIDO" FROM LIBROS

-- EJERCICIO 6
SELECT AUTOR, SUBSTR(AUTOR,INSTR(AUTOR,',')+1)"NOMBRE" FROM LIBROS

-- EJERCICIO 7
SELECT SUBSTR(AUTOR,1,INSTR(AUTOR,',')-1)"APELLIDO", SUBSTR(AUTOR,INSTR(AUTOR,',')+1)"NOMBRE" FROM LIBROS

-- EJERCICIO 8
SELECT TITULO FROM LIBROS ORDER BY LENGTH(TITULO)

-- MOSTRAR SIGLAS (APELLIDO+NOMBRE(C.C.))
SELECT CONCAT(SUBSTR(AUTOR,1,1)||'.', SUBSTR(SUBSTR(AUTOR,INSTR(AUTOR,',')+1),2,1)||'.')"INICIALES"  FROM LIBROS

-- EJERCICIO 9
SELECT NOMBRE, FECHANAC FROM NACIMIENTOS
  

