-- EJERCICIO 1 -- 
SELECT OFICIO, SUM(SALARIO)"SUMA SALARIOS" FROM EMPLE
WHERE DEPT_NO = (SELECT DEPT_NO FROM DEPART WHERE DNOMBRE = 'VENTAS')
GROUP BY OFICIO

-- EJERCICIO 2 --
SELECT APELLIDO FROM EMPLE E WHERE SALARIO = (SELECT AVG(SALARIO) FROM EMPLE WHERE E.DEPT_NO=DEPT_NO)

-- EJERCICIO 3 --
SELECT DEPT_NO, COUNT(*)"Nº EMPLEADOS" FROM EMPLE WHERE OFICIO='EMPLEADO' GROUP BY DEPT_NO

-- EJERCICIO 4 --
SELECT DEPT_NO, COUNT(*)"Nº EMPLEADOS" FROM EMPLE WHERE OFICIO='EMPLEADO' GROUP BY DEPT_NO

-- EJERCICIO 5 --
SELECT 