-- EJERCICIO 1
SELECT TRUNC(AVG(SALARIO),2)"MEDIA SUELDO", COUNT(COMISION) "COMISIONES", MAX(SALARIO) "SALARIO MAXIMO", MIN(SALARIO)"SALARIO MINIMO" 
FROM EMPLE WHERE DEPT_NO='30'

-- EJERCICIO 2
SELECT TEMA FROM LIBRERIA WHERE TEMA LIKE '%E%' AND EJEMPLARES=(SELECT MAX(EJEMPLARES) FROM LIBRERIA WHERE TEMA LIKE '%E%')

-- EJERCICIO 3
