CREATE TABLE ACTIVIDAD4
( 
  DNI VARCHAR2(10) PRIMARY KEY,
  NOMBRE VARCHAR2(30) NOT NULL,
  EDAD NUMBER(3) CHECK (EDAD BETWEEN 5 AND 20),
  CURSO NUMBER(3) CHECK (CURSO IN 1, 2, 3),
  CONSTRAINT NOMBRE CHECK (NOMBRE = UPPER(NOMBRE))
);

INSERT INTO ACTIVIDAD4
VALUES ('123456789A', 'SERGIO', 6, 2);