DROP TABLE ARTICULOS2;
DROP TABLE FABRICANTES2;
CREATE TABLE FABRICANTES2
( 
  COD_FABRICANTE NUMBER(3) PRIMARY KEY,
  NOMBRE VARCHAR2(15) CHECK (NOMBRE = UPPER(NOMBRE)),
  PAIS VARCHAR2(15) CHECK (PAIS = UPPER(PAIS))
);
CREATE TABLE ARTICULOS2
( 
  ARTICULO VARCHAR2(20) NOT NULL,
  COD_FABRICANTE NUMBER(3) NOT NULL REFERENCES FABRICANTES2,
  PESO NUMBER(3) NOT NULL CHECK(PESO>0),
  CATEGORIA VARCHAR2(15) NOT NULL CHECK (CATEGORIA IN ('Primera', 'Segunda', 'Tercera')) ,
  PRECIO_VENTA NUMBER(6,2) CHECK(PRECIO_VENTA>0),
  PRECIO_COSTO NUMBER(6,2) CHECK(PRECIO_COSTO>0),
  EXISTENCIAS NUMBER(5),
  CONSTRAINT PK_ART PRIMARY KEY (ARTICULO, PESO, CATEGORIA)
);

INSERT INTO FABRICANTES2
VALUES (123, 'ARROCES CANSINO', 'ESPAÑA');

INSERT INTO ARTICULOS2
VALUES ('ARROZ', 123, 2, 'Primera', 4, 2, 30);	