
CREATE TABLE PROVINCIAS
( 
  CODPROVIN NUMBER(2) PRIMARY KEY,
  NOM_PROVINCIA VARCHAR2(15)
);


CREATE TABLE PERSONAS
(
  DNI NUMBER(8) PRIMARY KEY,
  NOMBRE  VARCHAR2(15),
  DIRECCION VARCHAR(25),
  POBLACION VARCHAR2(20),
  CODPROVIN NUMBER(2) NOT NULL REFERENCES PROVINCIAS
);

INSERT INTO PROVINCIAS
VALUES (15, 'VALENCIA');

INSERT INTO PROVINCIAS
VALUES (23, 'CUENCA');

INSERT INTO PROVINCIAS
VALUES (31, 'MADRID');

INSERT INTO PERSONAS
VALUES (11111111, 'SERGIO', 'CALLE A', 'CUENCA', 23);

INSERT INTO PERSONAS
VALUES (22222222, 'DANIEL', 'CALLE B', 'VALENCIA', 15);

INSERT INTO PERSONAS
VALUES (33333333, 'AINHOA', 'CALLE C', 'MADRID', 31);