-- EJERCICIO 1 --
SELECT NOMFACULTAD 
FROM FACULTAD 
WHERE IDFACULTAD IN (SELECT IDFACULTAD 
                     FROM INVESTIGADORES 
                     GROUP BY IDFACULTAD 
                     HAVING COUNT(DNI)=2);

-- EJERCICIO 2 -- 

SELECT DNI, NOMBRE FROM INVESTIGADORES 
WHERE IDFACULTAD NOT IN (SELECT IDFACULTAD FROM EQUIPOS WHERE IDEQUIPO IN (SELECT IDEQUIPO FROM RESERVA));
-- EJERCICIO 3 --
SELECT NOMBRE, APELLIDOS FROM INVESTIGADORES 
WHERE DNIJEFE IN (SELECT DNI FROM INVESTIGADORES WHERE APELLIDOS='ANGUERA VILAFRANCA')
AND IDFACULTAD IN (SELECT IDFACULTAD FROM INVESTIGADORES GROUP BY IDFACULTAD HAVING COUNT(DNI)>1);

-- EJERCICIO 4 --
SELECT IDRESERVA, DNI, IDEQUIPO, 
REGEXP_REPLACE(TO_CHAR(FECHAINICIO, '"del "day" "d"')||
               TO_CHAR(FECHAFIN, '" al "day" "d" de "month" de "yyyy"'),'*  *',' ')"informe_fechas" 
FROM RESERVA
WHERE IDEQUIPO IN 
(SELECT IDEQUIPO FROM RESERVA GROUP BY IDEQUIPO 
HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM RESERVA GROUP BY IDEQUIPO));


-- EJERCICIO 5 --


-- EJERCICIO 6 --
SELECT IDFACULTAD, NOMFACULTAD FROM FACULTAD
WHERE IDFACULTAD IN (SELECT IDFACULTAD FROM EQUIPOS 
                     GROUP BY IDFACULTAD HAVING SUM(PRECIO) IN
                                      (SELECT MIN(SUM(PRECIO)) FROM EQUIPOS GROUP BY IDEQUIPO));

                     

