-- EJERCICIO 1 --
CREATE TABLE PEDIDOS2
(
  NIF VARCHAR2(10),
  ARTICULO VARCHAR2(20),
  COD_FABRICANTE NUMBER(3),
  PESO NUMBER(3),
  CATEGORIA VARCHAR2(10) CHECK (CATEGORIA IN ('Primera', 'Segunda', 'Tercera')),
  FECHA_PEDIDO DATE,
  UNIDADES_PEDIDAS NUMBER(4) CHECK(UNIDADES_PEDIDAS > 0),
  CONSTRAINT PK_PEDIDOS PRIMARY KEY (NIF,ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_PEDIDO),
  CONSTRAINT FK_ARTICULOS FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULOS ON DELETE CASCADE,
  CONSTRAINT FK_TIENDAS FOREIGN KEY (NIF) REFERENCES TIENDAS,
  CONSTRAINT FK_FABRICANTES FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES
);

CREATE TABLE VENTAS2
(
  NIF VARCHAR2(10),
  ARTICULO VARCHAR2(20),
  COD_FABRICANTE NUMBER(3) REFERENCES FABRICANTES,
  PESO NUMBER(3),
  CATEGORIA VARCHAR2(10) CHECK (CATEGORIA IN ('Primera', 'Segunda', 'Tercera')),
  FECHA_VENTA DATE,
  UNIDADES_VENDIDAS NUMBER(4) CHECK(UNIDADES_VENDIDAS > 0),
  CONSTRAINT PK_PEDIDOS PRIMARY KEY (NIF,ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_VENTA),
  CONSTRAINT FK_ARTICULOS FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULOS ON DELETE CASCADE,
  CONSTRAINT FK_TIENDAS FOREIGN KEY (NIF) REFERENCES TIENDAS,
  CONSTRAINT FK_FABRICANTES FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES
);
-- EJERCICIO 2 --

-- EJERCICIO 3 --
ALTER TABLE PEDIDOS MODIDY (UNIDADES_PEDIDAS NUMBER(6));
ALTER TABLE PEDIDOS MODIDY (UNIDADES_VENDIDAS NUMBER(6));

-- EJERCICIO 4 --
ALTER TABLE TIENDAS
ADD CONSTRAINT TIENDA_T
CHECK (PROVINCIA != 'TOLEDO') NOVALIDATE

-- EJERCICIO 5 --
ALTER TABLE PEDIDOS ADD(PVP NUMBER(6,2));
ALTER TABLE VENTAS ADD(PVP NUMBER(6,2));

-- EJERCICIO 6 --
CREATE OR REPLACE VIEW CONSERJES
AS SELECT C.NOMBRE, P.APELLIDOS
FROM CENTROS C, PERSONAL P
WHERE C.COD_CENTRO = P.COD_CENTRO AND FUNCION = 'CONSERJE'

-- EJERCICIO 7 --
CREATE SYNONYM CONSER FOR CONSERJES
