DROP TABLE MARCAS;
DROP TABLE CLIENTES;
DROP TABLE CONCESIONARIOS;
DROP TABLE COCHES;
DROP TABLE DISTRIBUCION;
DROP TABLE VENTAS;

CREATE TABLE MARCAS
(
	CIFM 	NUMBER(4) PRIMARY KEY,
	NOMBRE 	VARCHAR2(10),
	CIUDAD 	VARCHAR2(15)
);

CREATE TABLE CLIENTES
(
	DNI 	VARCHAR2(9) PRIMARY KEY,
	NOMBRE 	VARCHAR2(20),
	APELLIDO VARCHAR2(40),
	CIUDAD 	VARCHAR2(15),
  
	CONSTRAINT MAYUS_NOMBRE CHECK (NOMBRE = INITCAP (NOMBRE)),
	CONSTRAINT MAYUS_APE CHECK (APELLIDO = INITCAP (APELLIDO))
);

CREATE TABLE CONCESIONARIOS
(
	CIFC 	NUMBER(4) PRIMARY KEY,
	NOMBRE 	VARCHAR2(4),
	CIUDAD 	VARCHAR2(15) CHECK (CIUDAD IN ('CUENCA','GUADALAJARA','TOLEDO','CIUDAD REAL','ALBACETE'))
);

CREATE TABLE COCHES
(
	CODCOCHE NUMBER(4) PRIMARY KEY,
	NOMBRE 	VARCHAR2(10),
	MODELO 	VARCHAR2(10),
	CIFM 	NUMBER(4) REFERENCES MARCAS
);

CREATE TABLE DISTRIBUCION
(
	CIFC 	NUMBER(4) REFERENCES CONCESIONARIOS,
	CODCOCHE NUMBER(4) REFERENCES COCHES,
	CANTIDAD NUMBER(2) CHECK (CANTIDAD BETWEEN 0 AND 10)
);


CREATE TABLE VENTAS
(
	CIFC 	NUMBER(4) REFERENCES CONCESIONARIOS,
	DNI 	VARCHAR2(9) REFERENCES CLIENTES,
	CODCOCHE NUMBER(4) REFERENCES COCHES,
	COLOR 	VARCHAR2(10) 
			CHECK (COLOR IN ('BLANCO','AZUL','VERDE','ROJO')),
  
  CONSTRAINT BLANCO_ROJO CHECK ((CIFC=0001) AND (COLOR='BLANCO') OR (CIFC=0001) AND (COLOR='ROJO'))
);

-- NO SE PUEDE REALIZAR UNA ACTUALIZACION SOBRE ESTA VISTA PORQUE TIENE UNA EXPRESION DE GRUPO --
CREATE OR REPLACE VIEW DISTRIBUCIONES
AS SELECT C.NOMBRE, MODELO, M.NOMBRE
FROM COCHES C, MARCAS M
WHERE C.NOMBRE = M.NOMBRE
GROUP BY C.NOMBRE, MODELO, M.NOMBRE