CREATE TABLE AAMARCAS(

CIFM     NUMBER(4) PRIMARY KEY,
NOMBRE   VARCHAR2(10),
CIUDAD   VARCHAR2(12)

);

CREATE TABLE AACLIENTES(

DNI        NUMBER(4) PRIMARY KEY,
NOMBRE     VARCHAR2(10) CHECK(NOMBRE=INITCAP(NOMBRE)),
APELLIDO   VARCHAR2(15) ,
CUIDAD     VARCHAR2(15)

);

CREATE TABLE AACONCESIONARIOS(

CIFC     NUMBER(4) PRIMARY KEY,
NOMBRE   VARCHAR(8),
CIUDAD   VARCHAR(10) CHECK(CIUDAD IN ('Cuenca','Albacete','Guadalajara','Toledo'))

);
CREATE TABLE AACOCHES(

CODCOCHE   NUMBER(4) PRIMARY KEY,
NOMBRE     VARCHAR2(10),
MODELO     VARCHAR2(10),
CIFM       NUMBER(4) ,

FOREIGN KEY (CIFM)  REFERENCES AAMARCAS

);
CREATE TABLE AADISTRIBUCION(

CIFC         NUMBER(4)  ,
CODCOCHE     NUMBER(4),
CANTIDAD     NUMBER(3) PRIMARY KEY CHECK(CANTIDAD<=10),

FOREIGN KEY (CODCOCHE) REFERENCES AACOCHES,
FOREIGN KEY (CIFC)  REFERENCES AACONCESIONARIOS

);
CREATE TABLE AAVENTAS(

CIFC         NUMBER(4),
DNI          NUMBER(4),
CODCOCHE     NUMBER(4),
COLOR        VARCHAR(10) PRIMARY KEY CHECK(COLOR IN ('rojo','azul','verde')),

FOREIGN KEY (CODCOCHE) REFERENCES AACOCHES,
FOREIGN KEY (CIFC)  REFERENCES AACONCESIONARIOS,
FOREIGN KEY (DNI) REFERENCES AACLIENTES

);