-- EJERCICIO 1 --
CREATE OR REPLACE VIEW CL_FIJO
AS SELECT DNI, NOMBRE, CIUDAD
FROM CLIENTES
WHERE DNI IN (SELECT DNI FROM CONTRATOS
              WHERE CONTRATO = 'FIJO'
              GROUP BY DNI
              HAVING COUNT(*) > 1);
              
-- EJERCICIO 2 --
CREATE VIEW CRED_6
AS SELECT COD_ASIGNATURA, NOMBRE_ASIGNATURA, NOMBRE, APELLIDO
FROM ASIGNATURA A, PROFESOR P, PERSONA PE
WHERE P.DNI = PE.DNI AND P.DNI = A.DNI AND CREDITOS > 6 AND EXPERIENCIA > 3;