**1***

ALTER TABLE DISTRIBUCION MODIFY(CANTIDAD NUMBER(4))

ALTER TABLE COCHES MODIFY(COCHES VARCHAR(40))

**2***

ALTER TABLE AACOCHES ADD STOCK NUMBER(2) CHECK(STOCK<100);



AFTER TABLE AACLIENTES ADD TELEFONO VARCHAR(9) 

UPDATE AACLIENTES
SET TELEFONO='999999999'

AFTER TABLE AACLIENTES MODIFY TELEFONO COSTRAINT TEFEFONO NOT NULL 

***3***

AFTER TABLE COCHES ADD CONSTRAINT AUDI CHECK( (CIFM<>0004) OR( CIFM=0004 AND MODELO <> 'gti'))

***4***

CREATE OR REPLACE VIEW COCHE
AS SELECT NOMCOCHE, MODELO, NOMBRE, CANTIDAD
FROM MARCAS M, COCHES C, DISTRIBUCION D
WHERE D.
GROUP BY CIFC
HAVING COUNT(*)<1