-- EJERCICIO 1 --
CREATE OR REPLACE VIEW CL_FIJO
AS SELECT DNI, NOMBRE, CIUDAD
FROM CLIENTES
WHERE DNI IN (SELECT DNI FROM CONTRATOS
              WHERE CONTRATO = 'FIJO'
              GROUP BY DNI
              HAVING COUNT(*) > 1);
              
-- EJERCICIO 2 --
