DROP TABLE PERSONA;
DROP TABLE PROFESOR;
DROP TABLE ALUMNO;
DROP TABLE ASIGNATURA;
DROP TABLE MATRICULA;

CREATE TABLE PERSONA
(
  DNI 				VARCHAR2(9) PRIMARY KEY CHECK (SUBSTR(DNI,9,1)=UPPER(SUBSTR(DNI,9,1),
  NOMBRE 			VARCHAR2(30) NOT NULL,
  APELLIDO 		VARCHAR2(30) NOT NULL,
  FECHANAC 		DATE,
  SEXO 				CHAR(1) CHECK (SEXO IN ('H','M')),
  PADRE       VARCHAR2(9) REFERENCES PERSONA
  CONSTRAINT NOM+APE UNIQUE (NOMBRE,APELLIDO)
);

CREATE TABLE PROFESOR
(
  DNI 				VARCHAR2(9) PRIMARY KEY FOREIGN KEY REFERENCES PERSONA,
  EXPERIENCIA VARCHAR2(2) NOT NULL CHECK (EXPERIENCIA > 0)
);

CREATE TABLE ALUMNO
(
  DNI 				VARCHAR2(9) PRIMARY KEY FOREIGN KEY REFERENCES PERSONA,
  RESIDENCIA 	VARCHAR2(2) NOT NULL CHECK (RESIDENCIA IN ('SI','NO'))
);

CREATE TABLE ASIGNATURA
(
  COD_ASIGNATURA 	  NUMBER(3) PRIMARY KEY,
  NOMBRE_ASIGNATURA VARCHAR2(30) NOT NULL,
  CREDITOS 			    NUMBER(2) NOT NULL CHECK (CREDITOS IN (BETWEEN 1 AND 10)),
  DNI 				      VARCHAR2(9) FOREIGN KEY REFERENCES PROFESOR
);

CREATE TABLE MATRICULA
(
  DNI 				    VARCHAR2(9) FOREIGN KEY REFERENCES PERSONA,
  COD_ASIGNATURA 	NUMBER(3) FOREIGN KEY REFERENCES ASIGNATURA,
  AÑO 				    DATE,
  PRECIO 			    NUMBER(3) CHECK ((AÑO < 2000 AND PRECIO = 100) OR 
                                  ((AÑO>2000 AND AÑO<2010) AND PRECIO = 150) OR
                                  (AÑO > 2010 AND PRECIO = 200)),
  
);