DROP TABLE PERSONA;
DROP TABLE PROFESOR;
DROP TABLE ALUMNO;
DROP TABLE ASIGNATURA;
DROP TABLE MATRICULA;

CAMBIAR TIPOS DE DATOS
CAMBIAR TIPOS DE DATOSCAMBIAR TIPOS DE DATOSCAMBIARCAMBIAR TIPOS DE DATOSv
CAMBIAR TIPOS DE DATOSCAMBIAR TIPOS DE DATOSCAMBIARCAMBIAR TIPOS DE DATOS
CAMBIAR TIPOS DE DATOS
CAMBIAR TIPOS DE DATOS
CAMBIAR TIPOS DE DATOS
CAMBIAR TIPOS DE DATOS
CAMBIAR TIPOS DE DATOSCAMBIAR

CREATE TABLE PERSONA
(
  DNI 				VARCHAR2(9) PRIMARY KEY,
  NOMBRE 			VARCHAR2(30),
  APELLIDO 		VARCHAR2(30),
  FECHANAC 		VARCHAR2(30),
  SEXO 				NUMBER(3),
  PADRE 			NUMBER(3) REFERENCES PERSONA
);

CREATE TABLE PROFESOR
(
  DNI 				VARCHAR2(9) PRIMARY KEY REFERENCES PERSONA,
  EXPERIENCIA VARCHAR2(30)
);

CREATE TABLE ALUMNO
(
  DNI 				VARCHAR2(9) PRIMARY KEY REFERENCES PERSONA,
  RESIDENCIA 	VARCHAR2(30)
);

CREATE TABLE ASIGNATURA
(
  COD_ASIGNATURA 	  VARCHAR2(9) PRIMARY KEY,
  NOMBRE_ASIGNATURA VARCHAR2(30),
  CREDITOS 			    VARCHAR2(9),
  DNI 				      VARCHAR2(9) REFERENCES PROFESOR
);

CREATE TABLE MATRICULA
(
  DNI 				    VARCHAR2(9) REFERENCES ALUMNO,
  COD_ASIGNATURA 	VARCHAR2(30) REFERENCES ASIGNATURA,
  AÑO 				    VARCHAR2(9),
  PRECIO 			    VARCHAR2(9)
);