-- EJERCICIO 1
SELECT MEDICO, APELLIDO, NOMBRE FROM MEDICOS WHERE ESPECIALIDAD='2' AND UNIVERSIDAD LIKE "%MADRID%"

-- EJERCICIO 2
SELECT NOMBRE, APELLIDOS FROM ENFERMEROS WHERE SEXO="M" AND

-- EJERCICIO 3
SELECT NOMBRE, APELLIDOS, EDAD, POBLACION FROM PACIENTES WHERE CODIGOPOSTAL LIKE "28%" AND TELEFONO LIKE "%54"

-- EJERCICIO 4


-- EJERCICIO 5
SELECT NOMBRE, APELLIDOS, NOMBRE_ENFERMEDAD FROM PACIENTES, ENFERMEDADES WHERE ORIGEN="VIRICO" AND AÑO_DESCUBRIMIENTO>="1925"

-- EJERCICIO 6
SELECT * FROM PACIENTES WHERE FECHA_ALTA IS NULL

-- EJERCICIO 7
SELECT * FROM PACIENTES WHERE DNI IN (SELECT DNI FROM INGRESOS WHERE COD_ENFERMEDAD IN (SELECT COD_ENFERMEDAD FROM ENFERMEDADES WHERE NOMBRE="HEPATITIS"))

-- EJERCICIO 8
SELECT * FROM MEDICOS WHERE COD_MEDICO NOT EXISTS IN (SELECT COD_MEDICO FROM PACIENTE)
