-- 1
SELECT * FROM ALUM0405;
-- 2
SELECT DNI, NOMBRE, APELLIDOS, CURSO, NIVEL, CLASE FROM ALUM0405;
-- 3
SELECT * FROM ALUM0405
WHERE POBLACION='GUADALAJARA';
-- 4
SELECT NOMBRE, APELLIDOS FROM ALUM0405
WHERE POBLACION='GUADALAJARA';
-- 5
SELECT DNI, NOMBRE, APELLIDOS, CURSO, NIVEL, CLASE FROM ALUM0405
ORDER BY APELLIDOS, NOMBRE;
-- 6
SELECT * FROM EMPLE WHERE APELLIDO LIKE 'J_'
-- 7
SELECT * FROM EMPLE WHERE APELLIDO LIKE '_R%'
-- 8
SELECT * FROM EMPLE WHERE APELLIDO LIKE 'A%O%'
-- 9
SELECT APENOM FROM ALUMNOS WHERE DNI IN (SELECT DNI FROM NOTAS WHERE COD IN (SELECT COD FROM ASIGNATURAS WHERE NOMBRE='FOL'))
-- 10
SELECT APENOM FROM ALUMNOS WHERE DNI IN (SELECT DNI FROM NOTAS 
WHERE NOTA BETWEEN '7' AND '8' AND COD IN (SELECT COD FROM ASIGNATURAS WHERE NOMBRE='FOL'))
-- 11
SELECT NOMBRE FROM ASIGNATURAS WHERE COD NOT IN (SELECT COD FROM NOTAS WHERE NOTA<5)