REM 1
SELECT * FROM ALUM0405;
REM 2
SELECT DNI, NOMBRE, APELLIDOS, CURSO, NIVEL, CLASE FROM ALUM0405;
REM 3
SELECT * FROM ALUM0405
WHERE POBLACION='GUADALAJARA';
REM 4
SELECT NOMBRE, APELLIDOS FROM ALUM0405
WHERE POBLACION='GUADALAJARA';
REM 5
SELECT DNI, NOMBRE, APELLIDOS, CURSO, NIVEL, CLASE FROM ALUM0405
ORDER BY APELLIDOS, NOMBRE;
REM 6
SELECT * FROM EMPLE WHERE APELLIDO LIKE 'J_'
REM 7
SELECT * FROM EMPLE WHERE APELLIDO LIKE '_R%'
REM 8
SELECT * FROM EMPLE WHERE APELLIDO LIKE 'A%O%'