-- 1
SELECT * FROM ALUM0405;
-- 2
SELECT DNI, NOMBRE, APELLIDOS, CURSO, NIVEL, CLASE FROM ALUM0405;
-- 3
SELECT * FROM ALUM0405
WHERE POBLACION='GUADALAJARA';
-- 4
SELECT NOMBRE, APELLIDOS FROM ALUM0405
WHERE POBLACION='GUADALAJARA';
-- 5
SELECT DNI, NOMBRE, APELLIDOS, CURSO, NIVEL, CLASE FROM ALUM0405
ORDER BY APELLIDOS, NOMBRE;
-- 6
SELECT * FROM EMPLE WHERE APELLIDO LIKE 'J_'
-- 7
SELECT * FROM EMPLE WHERE APELLIDO LIKE '_R%'
-- 8
SELECT * FROM EMPLE WHERE APELLIDO LIKE 'A%O%'