-- TABLA EMPLE Y DEPART
-- EJERCICIO 1
SELECT * FROM DEPART WHERE LOC LIKE 'B%'

-- EJERCICIO 2
SELECT EMP_NO, APELLIDO, OFICIO FROM EMPLE, DEPART
WHERE DEPT_NO IN (SELECT DEPT_NO FROM DEPART WHERE DNOMBRE IN ('VENTAS','CONTABILIDAD'))

-- EJERCICIO 3
SELECT * FROM EMPLE ORDER BY OFICIO, APELLIDO DESC

-- EJERCICIO 4
SELECT EMP_NO, APELLIDO, SALARIO, COMISION FROM EMPLE WHERE DIR IS NULL

-- EJERCICIO 5
SELECT APELLIDO, OFICIO, FECHA_ALT, SALARIO+COMISION "SALARIO TOTAL" FROM EMPLE WHERE COMISION IS NOT NULL AND COMISION>0


-- TABLAS LIBRERIA
-- EJERCICIO 1
SELECT TEMA, EJEMPLARES FROM LIBRERIA WHERE ESTANTE IN ('A','C')

-- EJERCICIO 2
SELECT ESTANTE FROM LIBRERIA WHERE TEMA='DIBUJO'


-- TABLAS ALUMNOS, ASIGNATURAS Y NOTAS
-- EJERCICIO 1
SELECT AL.DNI, APENOM, N.NOTA FROM ALUMNOS AL, NOTAS N
WHERE N.DNI=AL.DNI AND COD IN (SELECT COD FROM ASIGNATURAS WHERE COD=6)

-- EJERCICIO 2
SELECT DNI, APENOM, DIREC FROM ALUMNOS WHERE POBLA='Madrid' AND TELEF LIKE '916%'

--EJERCICIO 3
SELECT NOMBRE FROM ASIGNATURAS WHERE NOMBRE LIKE '%.%'

--EJERCICIO 4
SELECT NOMBRE, NOTA FROM ASIGNATURAS A, NOTAS N 
WHERE A.COD=N.COD AND DNI IN (SELECT DNI FROM ALUMNOS WHERE APENOM LIKE'Cerrato Vela, Luis')