SELECT NOMBRE FROM ALUM INTERSECT
(SELECT NOMBRE FROM NUEVOS UNION
SELECT NOMBRE FROM ANTIGUOS);

(SELECT NOMBRE FROM ALUM INTERSECT
SELECT NOMBRE FROM NUEVOS) UNION 
(SELECT NOMBRE FROM ALUM INTERSECT
SELECT NOMBRE FROM ANTIGUOS);

SELECT NOMBRE FROM ALUM
WHERE NOMBRE IN (SELECT NOMBRE FROM NUEVOS UNION SELECT NOMBRE FROM ANTIGUOS)

