-- EJERCICIO 1 --
ALTER TABLE DISTRIBUCION
MODIFY CANTIDAD number(4);

ALTER TABLE COCHES
MODIFY NOMBRE varchar2(40);

-- EJERCICIO 2 --
ALTER TABLE COCHES
ADD STOCK number(2);

ALTER TABLE COCHES 
ADD CONSTRAINT STOCK_MAX100 CHECK (STOCK<100);

ALTER TABLE CLIENTES
ADD TELEFONO varchar(9);

UPDATE CLIENTES
SET TELEFONO='999999999'

ALTER TABLE CLIENTES MODIFY TELEFONO CONSTRAINT TEFEFONO NOT NULL 

-- EJERCICIO 3 --
ALTER TABLE COCHES ADD CONSTRAINT AUDI CHECK((cifm<>'0004') OR (cifm='0004' AND MODELO <> 'gti'))

-- EJERCICIO 4 --

CREATE OR REPLACE VIEW VISTA_COCHES
AS SELECT c.nombre, c.modelo, m.nombre"MARCA", sum(cantidad)"VENDIDOS"
FROM COCHES C, MARCAS M, DISTRIBUCION D
WHERE C.CODCOCHE = D.CODCOCHE AND C.CIFM = M.CIFM AND D.CODCOCHE IN (SELECT CODCOCHE FROM DISTRIBUCION GROUP BY CODCOCHE HAVING COUNT(CIFC)>1)
GROUP BY C.NOMBRE, C.MODELO, M.NOMBRE