-- EJERCICIO 1 --

CREATE TABLE PEDIDOS2
(
  NIF VARCHAR2(10),
  ARTICULO VARCHAR2(20),
  COD_FABRICANTE NUMBER(3),
  PESO NUMBER(3),
  CATEGORIA VARCHAR2(10) CHECK (CATEGORIA IN ('Primera', 'Segunda', 'Tercera')),
  FECHA_PEDIDO DATE,
  UNIDADES_PEDIDAS NUMBER(4) CHECK(UNIDADES_PEDIDAS > 0),
  CONSTRAINT PK_PEDIDOS PRIMARY KEY (NIF,ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_PEDIDO),
  CONSTRAINT FK_ARTICULOS FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULOS ON DELETE CASCADE,
  CONSTRAINT FK_TIENDAS FOREIGN KEY (NIF) REFERENCES TIENDAS,
  CONSTRAINT FK_FABRICANTES FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES
);

CREATE TABLE VENTAS2
(
  NIF VARCHAR2(10),
  ARTICULO VARCHAR2(20),
  COD_FABRICANTE NUMBER(3) REFERENCES FABRICANTES,
  PESO NUMBER(3),
  CATEGORIA VARCHAR2(10) CHECK (CATEGORIA IN ('Primera', 'Segunda', 'Tercera')),
  FECHA_VENTA DATE,
  UNIDADES_VENDIDAS NUMBER(4) CHECK(UNIDADES_VENDIDAS > 0),
  CONSTRAINT PK_PEDIDOS PRIMARY KEY (NIF,ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_VENTA),
  CONSTRAINT FK_ARTICULOS FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULOS ON DELETE CASCADE,
  CONSTRAINT FK_TIENDAS FOREIGN KEY (NIF) REFERENCES TIENDAS,
  CONSTRAINT FK_FABRICANTES FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES
);