CREATE TABLE ALUMNOS07
(
  NUMERO_MATRICULA NUMBER(6) NOT NULL,
  NOMBRE  VARCHAR2(15)  NOT NULL,
  FECHA_NACIMIENTO DATE,
  DIRECCION VARCHAR2(30),
  LOCALIDAD VARCHAR2(15)
);

INSERT INTO ALUMNOS07
VALUES (123456, 'SERGIO', SYSDATE, 'CALLE X', 'CUENCA');


