-- EJERCICIO 1 --
INSERT INTO INVESTIGADORES
SELECT '321321321R', 'EDUARDO', APELLIDOS, IDFACULTAD, DNIJEFE 
FROM INVESTIGADORES
WHERE DNI = '234353433P';

-- EJERCICIO 2 --
UPDATE INVESTIGADORES
SET NOMBRE = NOMBRE||'JEFE'
WHERE DNI IN (SELECT DNIJEFE FROM INVESTIGADORES
              GROUP BY DNIJEFE
              HAVING COUNT(*)>1);
              
-- EJERCICIO 3 --
DELETE FROM EQUIPOS
WHERE IDEQUIPO NOT IN (SELECT IDEQUIPO FROM RESERVA )
AND IDEQUIPO IN (SELECT IDEQUIPO FROM RESERVA WHERE FECHAINICIO < (TO_DATE('120905', 'ddmmyy')));

-- EJERCICIO 4 --
UPDATE EQUIPOS
SET PRECIO = PRECIO/1.1
WHERE IDFACULTAD = (SELECT IDFACULTAD FROM FACULTAD 
                    WHERE NOMFACULTAD = 'Ciencias Naturales' AND CIUDAD='Barcelona')
AND IDEQUIPO NOT IN (SELECT IDEQUIPO FROM RESERVA);

-- EJERCICIO 5 --
INSERT INTO EQUIPOS
SELECT 'K232', IDFACULTAD, 'Microprocesador i7', PRECIO*2
FROM EQUIPOS
WHERE DESCRIPCION = 'Cámara digital SONY';

-- EJERCICIO 6 --
DELETE FROM FACULTAD
WHERE IDFACULTAD IN (SELECT IDFACULTAD FROM EQUIPOS
                     GROUP BY IDFACULTAD
                     HAVING SUM(PRECIO)=(SELECT MAX(SUM(PRECIO)) FROM EQUIPOS
                                         GROUP BY IDFACULTAD));
                                         